### ISSUE TITLE
Examples of using with Typescript?

### ISSUE THREAD

**Issue by stbrody** [loune/s3leveldown#7]
Hi, are there any examples of how to use this in a Typescript repo?  I'm having trouble figuring out which packages and interfaces need to be used

**Comment by loune** [comment]
It should be quite straightforward. The `s3leveldown` npm package already includes [types](https://github.com/loune/s3leveldown/blob/master/s3leveldown.d.ts), but you might want `@types/levelup` from `levelup` types. So just `npm install s3leveldown aws-sdk levelup @types/levelup`. Then for `index.ts`
```ts
import levelup from 'levelup';
import s3leveldown from 's3leveldown';

const db = levelup(s3leveldown('my_bucket'));

db.put('name', 'test');
```

**Comment by stbrody** [comment]
Thank you for the quick reply!  My package is currently using [level-ts](https://www.npmjs.com/package/level-ts), but I guess we don't actually need that if we use `@levelup` instead?

Also you mention that we should specify the AWS region for a perf boost.  I guess to do that you need to provide the optional second argument to the `S3LevelDOWN` constructor with an `S3` instance and you set the region within that `S3` client object?

**Comment by loune** [comment]
From the readme of `level-ts` looks like it can wrap an instance of level db. So you could do `const db = new LevelTypescript(levelup(s3leveldown('my_bucket')))`

With the region, yes you could specify the region in a S3 client and pass it to s3leveldown. Alternatively, you could set the default region in your app globally like: 
```ts
import * as AWS from`aws-sdk`;
AWS.config.update({ region: 'ap-southeast-2' });
```

**Comment by stbrody** [comment]
Okay, great, thank you for your help!
